cc_library(
    name = "lib",
    srcs = [],
    hdrs = ["someip_controller.h"],
    visibility = ["//apps/common/someip_demon/code:__subpackages__"],
    deps = ["//apps/common/someip_demon/code/lib/controllers:core"],
)
