cc_library(
    name = "mock",
    hdrs = ["socket_stream_mock.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@srp_platform//bindings/common/socket:stream_socket_ipc",
        "@com_google_googletest//:gtest_main",
    ],
)
