cc_library(
    name = "core_controller",
    srcs = [],
    hdrs = ["core_controller_impl.h"],
    visibility = ["//apps/common/someip_demon/code/lib:__subpackages__"],
    deps = ["//apps/common/someip_demon/code/lib/controllers:interfaces"],
)
