---
- hosts: all
  tasks:
    - name: Run CppLint
      ansible.builtin.shell: |
        ./tools/cpplint/user_cpplint.sh
      args:
        chdir: "{{ zuul.project.src_dir }}"
        executable: /bin/bash
