---
- hosts: all
  tasks:
    - name: Run tests
      ansible.builtin.shell: |
        bazel test --config=pytest \
          //tests:core_all \
          --cache_test_results=no
      args:
        chdir: "{{ zuul.project.src_dir }}"
        executable: /bin/bash
