filegroup(
    name = "dtc_com_data_structure",
    srcs = ["dtc_com_frame.json","dtc_event_com_frame.json"],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "em_state_com_structure",
    srcs = ["em_state_com_frame.json"],
    visibility = ["//visibility:public"],
)