cc_library(
    name = "db",
    hdrs = [
        "database.h",
        "find_service_item.h",
        "service_item.h",
    ],
    deps = [
        "@srp_platform//ara/com:com_error_domain",
    ],
    visibility = ["@srp_platform//platform/common/someip_demon/code:__subpackages__"],
)
