- job:
    name: testjob
    run: playbooks/testjob.yaml
    nodeset:
      nodes:
        - name: ubuntu-qemu
          label: ubuntu-qemu

- project:
    check:
      jobs:
        - testjob
    gate:
      jobs:
        - testjob