- job:
    name: testjob
    run: playbooks/testjob.yaml
    nodeset:
      nodes:
        - name: ubuntu-qemu
          label: ubuntu-qemu
- job:
    name: cpplint
    run: .jobs/cpplint.yaml
- project:
    check:
      jobs:
        - testjob
        - cpplint
    gate:
      jobs:
        - testjob
        - cpplint