filegroup(
    name = "temp_job",
    srcs = [
        "temp_did.json",
        "@srp_platform//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["@srp_platform//visibility:public"],
)