cc_library(
    name = "Model_lib",
    hdrs = glob(["*.h"]),
    visibility = ["@srp_platform//platform:__subpackages__"],
    deps = [
        "@srp_platform//platform/com:instance_identifier_container",
        "@srp_platform//platform/core:Result",
    ],
)
