cc_library(
    name = "simba_json",
    srcs = ["json_parser.cc"],
    hdrs = ["json_parser.h"],
    visibility = ["@srp_platform//visibility:public"],
    deps = [
        "@com_json//:json",
    ],
)
