test_suite(
    name = "core_all",
    tests = [
        "//tests/core:ping_test",
        # "//tests/core:ssh_test",
        "//tests/core:uds_test",
        "//tests/core:uds_machine_state_did_test",
    ],
)
