cc_binary(
    name = "logger",
    srcs = [
        "main.cc",
    ],
    visibility = ["//platform/common/logger:__subpackages__"],
    deps = [
        "//platform/common/logger/model:ara",
        "//platform/common/logger/code/application:dlt_service_lib",
    ],
)
