cc_library(
    name = "Model_lib",
    hdrs = glob(["*.h"]),
    visibility = ["@srp_platform//ara:__subpackages__"],
    deps = [
        "@srp_platform//ara/com:instance_identifier_container",
        "@srp_platform//ara/core:Result",
    ],
)
