filegroup(
    name = "recovery_job",
    srcs = [
        "recovery_rid.json",
        "@srp_platform//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["@srp_platform//visibility:public"],
)