cc_library(
    name = "proxy",
    srcs = [
        "event.h",
        "proxy.h",
    ],
    visibility = ["@srp_platform//ara/com:__subpackages__"],
    deps = [
        "@srp_platform//ara/com:types",
        "@srp_platform//ara/core:instance_specifier",
    ],
)
