load("//tools/pytest:pytest_test.bzl", "pytest_test")

pytest_test(
    name = "ping_test",
    srcs = ["ping_test.py"],
    deps = [
    ],
)

pytest_test(
    name = "ssh_test",
    srcs = ["ssh_test.py"],
    deps = [
    ],
)

pytest_test(
    name = "uds_test",
    srcs = ["uds_test.py"],
    deps = [
    ],
)

pytest_test(
    name = "uds_machine_state_did_test",
    srcs = ["uds_machine_state_did_test.py"],
    deps = [
    ],
)
