filegroup(
    name = "gpio_mw_job",
    srcs = [
        "gpio_pin_did.json",
        "@srp_platform//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
