cc_test(
    name = "test_method",
    srcs = [
        "test_method.cc",
    ],
    visibility = ["//platform/com/skeleton/tests:__subpackages__"],
    deps = [
        "//platform/com/skeleton",
        "//platform/com/skeleton/tests/mocks",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_event",
    srcs = [
        "test_event.cc",
    ],
    visibility = ["//platform/com/skeleton/tests:__subpackages__"],
    deps = [
        "//platform/com/skeleton",
        "//platform/com/skeleton/tests/mocks",
        "@com_google_googletest//:gtest_main",
    ],
)