filegroup(
    name = "SM_service",
    srcs = [
        "example_service_depl.json",
        "sm_service.json",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sm_diag",
    srcs = [
        "sm_did.json",
        "@srp_platform//platform_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
