cc_library(
    name = "fifo_skeleton_lib",
    hdrs = [
        "fifo_skeleton.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@srp_platform//platform/com:com_error_domain",
        "@srp_platform//platform/core:instance_specifier",
    ],
)

cc_library(
    name = "fifo_proxy_lib",
    hdrs = [
        "fifo_proxy.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@srp_platform//platform/com:com_error_domain",
        "@srp_platform//platform/core:instance_specifier",
    ],
)
