# cc_library(
#     name = "multicast_controller",
#     srcs = ["multicast_controller.cc"],
#     hdrs = ["multicast_controller.h"],
#     visibility = ["@srp_platform//platform/common/someip_demon/code:__subpackages__"],
#     deps = [
#         "@srp_platform//platform/log",
#         "@srp_platform//platform/common/someip_demon/code/common:udp_lib",
#         "@srp_platform//platform/common/someip_demon/code/common/com:interface",
#     ],
# )
