cc_library(
    name = "core",
    srcs = [],
    hdrs = [],
    visibility = ["//apps/common/someip_demon/code:__subpackages__"],
    deps = [
        "//apps/common/someip_demon/code/lib/controllers:interfaces",
        "//apps/common/someip_demon/code/lib/controllers/impl:core_controller",
    ],
)

cc_library(
    name = "interfaces",
    srcs = [],
    hdrs = [
        "core_controller.h",
        "sd_controller.h",
    ],
    visibility = ["//apps/common/someip_demon/code:__subpackages__"],
    deps = [],
)
