# cc_test(
#     name = "test_routable_uds_service",
#     srcs = ["test_routable_uds_service.cc"],
#     features = ["test_target"],
#     deps = [
#         "@srp_platform//bindings/common/socket/mock",
#         # "@srp_platform//ara/diag/routing",
#         "@srp_platform//ara/diag/routing:routing_for_ut",
#     ],
# )
