cc_library(
    name = "mocks",
    hdrs = glob(["*.h"]),
    visibility = ["//platform/com/skeleton/tests:__subpackages__"],
    deps = ["//platform/com/skeleton:interfaces"],
    testonly = True,
)
