cc_test(
    name = "test_event",
    srcs = ["test_event.cc"],
    visibility = ["//ara/com/proxy/tests:__subpackages__"],
    deps = [
        "//ara/com/proxy",
        "//ara/com/proxy/tests/mocks",
        "@com_google_googletest//:gtest_main",
    ],
)
