# cc_library(
#     name = "IPC_Service",
#     hdrs = ["sm_service.h"],
#     visibility = ["@srp_platform//platform/common/em/code:__subpackages__"],
#     deps = [
#         "@srp_platform//platform/common/em/model:someip_lib",
#         "@srp_platform//platform/common/em/code/services/em:em_service",
#     ],
# )
