filegroup(
    name = "file_logger_job",
    srcs = [
        "file_logger_did.json",
        "@srp_platform//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["@srp_platform//visibility:public"],
)