cc_library(
    name = "ipc",
    srcs = [
        "ipc_controller.cc",
        "ipc_controller.h",
    ],
    visibility = ["//ara/com:__subpackages__"],
    deps = ["//bindings/common/controller:interfaces"],
)
