cc_library(
    name = "interface",
    hdrs = ["i_multicast_controller.h"],
    visibility = ["//platform/common/someip_demon/code:__subpackages__"],
    deps = [
        "@srp_platform//ara/core:Result",
        "//platform/common/someip_demon/code/common:controller",
    ],
)
