name: Check syntax

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install cpplint
        run: |
          sudo apt install cpplint

      - name: Check C++ Syntax
        run: |
          ./tools/cpplint/user_cpplint.sh 
