name: Self-Approve Action

on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  self-approve-action:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-Approve Action
        uses: nicklegan/github-repo-self-approve-action@v1.0.1
        # if: github.actor == 'bartoszsnieg'
        if: contains(github.event.comment.body, 'APPROVE')
        with:
          appid: ${{ secrets.APPID }}
          privatekey: ${{ secrets.PRIVATEKEY }}
          installationid: ${{ secrets.INSTALLATIONID }}